const dbConfig = require("../config/db.config.js");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.mongoose.set('useNewUrlParser', true);
db.mongoose.set('useFindAndModify', false);
db.mongoose.set('useCreateIndex', true);
db.url = dbConfig.url;
db.user = require("./user.model.js")(mongoose);
db.event = require("./event.model.js")(mongoose);
module.exports = db;